# https://github.com/marketplace/actions/image-actions
name: Compress images

on:
  # only fired on PR against master branch
  pull_request:
    branches: master

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          pngQuality: "100"
          webpQuality: "80"
          ignorePaths: "node_modules/**"
