name: frontend

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Npm install and build
      run: |
        cd frontend
        npm install
        echo "export const API_URL = 'http://localhost:5000/';" > config-local.js
        npm run build
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: bundle-js
        path: './frontend/dist/bundle.js'
